### PR TITLE
Use pytest

### PR DESCRIPTION
**Pull request by eugene-eeo**
Use PyTest as it is less verbose compared to vanilla unittest.

### CODE REVIEW

**Comment by msiemens** [comment]
+1 for PyTest. I use it in TinyDB too. IMO the main selling point is its assertion introspection ([example](pytest.org/latest/example/reportingdemo.html)).

**Comment by eugene-eeo** [comment]
@msiemens the link is broken... Most likely you mean [this](http://pytest.org/latest/example/reportingdemo.html)?

**Comment by msiemens** [comment]
Yes, that's what I mean :)

**Comment by rodricios** [comment]
Hi @msiemens, nice to meet you :) 

So are we ok to merge this one?

**Comment by msiemens** [comment]
Nice to meet you, @rodricios :) I think this PR is ready to go

**Pull request merged**
